# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: Development
  variables:
    solution: '**/Extranet.csproj'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.410'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true 
      /p:WebPublishMethod=Package 
      /p:PackageAsSingleFile=true 
      /p:SkipInvalidConfigurations=true 
      /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" 
      /p:DeployIisAppPath="Extranet.Dev"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'debug'
      publishLocation: 'Container'


- job: Production
  variables:
    solution: '**/Extranet.csproj'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.410'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true 
      /p:WebPublishMethod=Package 
      /p:PackageAsSingleFile=true 
      /p:SkipInvalidConfigurations=true 
      /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" 
      /p:DeployIisAppPath="Extranet.Prod"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'release'
      publishLocation: 'Container'